oftenUsed: split between header and cpp
Details: 
split the functions in oftenUsed between the header and the
implementation file.
Getting an error message when linking 
undefined reference to `oftenUsed::DeltaR'
I believe that's related to a modification I need to make somewhere in
the makefile; will finish it tomorrow.